parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true

env:
  node: true
  es6:  true

globals:
  global: true

extends:
  - eslint:recommended
